name: Deploy to ECS

on:
  push:
    branches:
      - staging

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2

      - name: Login to ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build Docker image
        run: |
          docker buildx build --platform linux/amd64 -t hello-world .

      - name: Tag Docker image
        run: |
          docker tag hello-world:latest ${{ secrets.ECR_URI }}:latest

      - name: Push Docker image
        run: |
          docker push ${{ secrets.ECR_URI }}:latest

      - name: Force ECS Deployment
        run: |
          aws ecs update-service \
            --cluster hello-world-c2 \
            --service hello-world-task-service \
            --force-new-deployment
